config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @list = List.find(params[:list_id])
    @items = @list.items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @list = List.find(params[:list_id])
  end

  def create
    @item = List.find(params[:list_id]).items.new(item_params)
    if @item.save
      redirect_to list_items_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])
    if @item.update(item_params)
      redirect_to list_items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_items_path
  end

  private
  # Strong params - allowing specific data to come into the controller. Security.
    def item_params
      params.require(:item).permit(:item, :description,
                                   :completed, :list_id)
    end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
    redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private
  # Strong params - allowing specific data to come into the controller. Security.
    def list_params
      params.require(:list).permit(:title, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for [@list, @item] do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item %>
  <br />

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br />

  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <br />

  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>
  Editing Item <%= @item.item %>
</h1>
<br />

<%= render(partial: 'form') %>

app/views/items/index.html.erb
<h1>Items Needed:</h1>
<hr />

<ul>
  <% @items.each do |item| %>
    <li>
      <%= item.item %> -
      <%= link_to 'Show', list_item_path(item.list_id, item.id) %> -
      <%= link_to 'Edit', edit_list_item_path(item.list_id, item.id) %> -
      <%= link_to 'Delete', list_item_path(item.list_id, item), method: :delete, data: {confirm: 'Are you sure you want to delete this item?'} %>

      <%= form_for [List.find(item.list_id), item] do |f| %>
        <%= f.label :completed %>
        <%= f.check_box :completed %>
        <br />
      <%= f.submit %>
      <% end %>

    </li>
  <% end %>
</ul>

<%= link_to 'New Item', new_list_item_path %>
<br />
<%= link_to 'Back to To-Do Lists', lists_path %>

app/views/items/new.html.erb
<h1>Add an Item</h1>
<hr />

<%= render(partial: 'form') %>

app/views/items/show.html.erb
<h1> <%= @item.item %> </h1>
<hr />


<blockquote>               <!--*******This is where I want my Items***********-->
  <%= @item.description %>
</blockquote>

<h6>
  Is the item completed? <%= @item.completed ? 'Yes' : 'No' %>
</h6>

<%= link_to 'Back', list_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoUpdated</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <br />

  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>
  Editing List With Name: <%= @list.title %>
</h1>
<br />

<%= render(partial: 'form') %>

app/views/lists/index.html.erb
<h1>Your To-Do Lists</h1>
<hr />

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= list.title %> -
      <%= link_to 'Show', list_path(list) %> -
      <%= link_to 'Edit', edit_list_path(list) %> -
      <%= link_to 'Delete', list_path(list), method: :delete, data: {confirm: 'Are you sure you want to delete this list?'} %>

      <%= form_for list do |f| %>
        <%= f.label :completed %>
        <%= f.check_box :completed %>
        <br />
      <%= f.submit %>
      <% end %>

    </li>
  <% end %>
</ul>

<%= link_to 'New To-Do List', new_list_path %>

app/views/lists/new.html.erb
<h1>Add To Your To Do List</h1>
<hr />

<%= render(partial: 'form') %>

app/views/lists/show.html.erb
<h1> <%= @list.title %> </h1>
<hr />


<h6>
  Is the list completed? <%= @list.completed ? 'Yes' : 'No' %>
</h6>

<%= link_to 'All Items', list_items_path(@list) %>
<br />
<%= link_to 'Back', lists_path %>